# Agent 1 Configuration
debug: true

providers:
  http-test:
    id: "http-test"
    type: "http"
    name: "HTTP Test Server"
  hf-public:
    id: "hf-public"
    type: "hf"
    name: "Hugging Face Public"
  peer-main:
    id: "peer-main"
    type: "peer"
    name: "Peer-to-Peer Transfer"

agent:
  id: "agent-1"
  controller_url: "http://localhost:8080"
  listen_addr: "http://0.0.0.0:8081"
  advertise_addr: "http://localhost:8081"
  heartbeat_interval: "10s"
  storage:
    base_path: "/tmp/syncbit-test/agent1"
    cache:
      ram_limit: "2GB"
      disk_limit: "0"
