# Controller Configuration
debug: true

providers:
  hf-public:
    id: "hf-public"
    type: "hf"
    name: "Hugging Face Public"

controller:
  listen_addr: "0.0.0.0:8080"
  agent_timeout: "60s"
  sync_interval: "5s"
